all:
    gcc Main.c gerenciar_prod.c gerenciar_prod.h  buscar_prod.c busca_prod.h cadastrar_cliente.c cadastro_cliente.h carinho_compres.c carinho_compras.h export_import.c export_import.h -o prog1.exe

run:
    ./prog1.exe
    